# Generated by Django 2.2.4 on 2019-08-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoperfil',
            options={'verbose_name_plural': 'EstadosPerfiles'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
    ]
